# Python Programming Assignment No. 08

                                                                                By

                                                                            Santhosh Kumar

# Question No. 01

#### Write a Python Program to Add Two Matrices?

In [37]:
import numpy as np

class Adding_two_matrix:

    def add_two_matrix(self):
        """This function will help you to add 2 matrix"""
        try:
            n1 = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
            n2 = np.matrix([[11,22,33],[44,55,66],[77,88,99]])
            result = n1 + n2
            print(f"Your first matrix is {n1}")
            print(f"Your second matrix is {n2}")
            print("\n")
            print(f"The addition of 2 matrix is")
            return result
        except Exception as e:
            print("You made a mistake on inside the adding two matrix funciton - ",e)

Adding_two_matrix = Adding_two_matrix()
Adding_two_matrix.add_two_matrix()

Your first matrix is [[1 2 3]
 [4 5 6]
 [7 8 9]]
Your second matrix is [[11 22 33]
 [44 55 66]
 [77 88 99]]


The addition of 2 matrix is


matrix([[ 12,  24,  36],
        [ 48,  60,  72],
        [ 84,  96, 108]])

# Question No. 02

#### Write a Python Program to Multiply Two Matrices?

In [38]:
import numpy as np

class Multiplying_two_matrix:

    def multiplying_two_matrix(self):
        """This function will help you to multiply 2 matrix"""
        try:
            n1 = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
            n2 = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
            result = n1 * n2
            print(f"Your first matrix is {n1}")
            print(f"Your second matrix is {n2}")
            print("\n")
            print(f"The multiplication of 2 matrix is")
            return result
        except Exception as e:
            print("You made a mistake on inside the adding two matrix funciton - ",e)

Multiplying_two_matrix = Multiplying_two_matrix()
Multiplying_two_matrix.multiplying_two_matrix()

Your first matrix is [[1 2 3]
 [4 5 6]
 [7 8 9]]
Your second matrix is [[1 2 3]
 [4 5 6]
 [7 8 9]]


The multiplication of 2 matrix is


matrix([[ 30,  36,  42],
        [ 66,  81,  96],
        [102, 126, 150]])

# Question No. 03

#### Write a Python Program to Transpose a Matrix?

In [40]:
class Transpose:

    def transpose_a_matrix(self):
        """This function will help you to transpose the matrix"""
        try:
            n1 = np.matrix([[1,2,3],[4,5,6],[7,8,9]])
            print(f"Your matrix is {n1}")
            trans = np.transpose(n1)
            print("\n")
            print("Matrix after transpose : ")          
            return trans
        except Exception as e:
            print("You made a mistake on inside the transpose a matrix function - ",e)

Transpose = Transpose()
Transpose.transpose_a_matrix()


Your matrix is [[1 2 3]
 [4 5 6]
 [7 8 9]]


Matrix after transpose : 


matrix([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])

# Question No. 04

#### Write a Python Program to Sort Words in Alphabetic Order?

In [47]:
class Alphabetic_Order:

    def words_in_alphabetical_order(self):
        """This function will help you to sort words in alphabetic order"""
        try:
            x = eval(input("Enter all of your words: "))
            print(f"Your input words is: {x}")
            print("\n")
            print(f"Words after sorting in alphabetical order")
            result = sorted(x)
            return result
        except Exception as e:
            print("You made a mistake inside words in alphabetical order function - ", e)

Alphabetic_Order = Alphabetic_Order()
Alphabetic_Order.words_in_alphabetical_order()

Your input words is: ['Nandhini', 'Janaki', 'Bharathi', 'Santhosh']


Words after sorting in alphabetical order


['Bharathi', 'Janaki', 'Nandhini', 'Santhosh']

# Question No. 05

#### Write a Python Program to Remove Punctuation From a String?

In [11]:
class Punctuation:

    def remove_punctuation(self):
        """This function will help you to remove the punctuations"""
        try:
            punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
            sentence = input("Enter your sentences here with punctuation: ")
            print(f"Your sentence is {sentence}")
            print("\n")
            for i in punctuations:
                for j in sentence:
                    if i in j:
                        sentence = sentence.replace(j, "")
            print("Sentence after removed punctuations")
            return sentence

        except Exception as e:
            print("You made a mistake inside the remove punctuation function - ", e)

Punctuation = Punctuation()
Punctuation.remove_punctuation()


Your sentence is I_neuron is the #% only best platform to learn data sciece than #% any colleges


Sentence after removed punctuations


'Ineuron is the  only best platform to learn data sciece than  any colleges'

                                            Completed

                                                                                     Santhosh Kumar